compile:
	javac -classpath .:classes:/opt/pi4j/lib/'*' -d . HomeEnvironment.java
run:
	java -classpath .:classes:/opt/pi4j/lib/'*' HomeEnvironment homeenvironment $(ip) 8004 26
runman:
	java -classpath .:classes:/opt/pi4j/lib/'*' HomeEnvironment homeenvironment 169.254.207.167 8004 26